import assert from 'node:assert/strict';
import { ExperimentJournal } from '../src/experiment-journal.js';
import { makeExperimentManifest } from '../src/experiment-manifest.js';
const journal = new ExperimentJournal(2);
const details = { temperature: 24, nested: { rain: false } };
journal.add('start', { neuralRun: 1, neuralMs: 0 }, details);
details.nested.rain = true;
assert.equal(journal.events[0].details.nested.rain, false);
const initial = journal.snapshot();
journal.add('restart', { neuralRun: 2, neuralMs: 0 });
journal.add('temperature', { neuralRun: 2, neuralMs: 100 }, { value: 28 });
assert.equal(initial.events.length, 1);
assert.equal(journal.snapshot().droppedEvents, 1);
assert.equal(journal.snapshot().completeRetainedHistory, false);
assert.deepEqual(journal.events.map(e => e.sequence), [2, 3]);
assert.throws(() => journal.events[0].details.value = 5);
assert.throws(() => new ExperimentJournal(0));
const environment = { tempC: 28, windKmh: 0 };
const manifest = makeExperimentManifest({ environment, interventions: journal.snapshot(), session: { id: 'session', neuralRun: 2 }, body: { health: 100 } });
environment.tempC = 99;
assert.equal(manifest.environment.tempC, 28);
assert.equal(manifest.session.neuralRun, 2);
assert.equal(manifest.interventions.events[1].sequence, 3);
assert.equal(makeExperimentManifest().environment, null);
console.log('PASS journal immutability, bounded history, explicit loss, run boundaries, manifest context snapshots');
