import assert from 'node:assert/strict';
import { parseSWC } from '../src/swc.js';
const options = { id: '10001', specimen: 'MaleCNS', nmPerUnit: 8 };
const raw = '# native voxel units\n1 1 0 0 0 1 -1\n2 3 3 4 0 1 1\n3 3 0 0 2 1 1\n';
const n = parseSWC(raw, options);
assert.equal(n.cableLengthNm, 56);
assert.equal(n.branchPoints, 1);
assert.equal(n.totalSegments, 2);
assert.deepEqual(n.segments[0], [24, 32, 0, 0, 0, 0]);
assert.equal(n.specimen, 'MaleCNS');
assert.equal(n.units, 'nm');
const truncated = parseSWC(raw, { ...options, maxSegments: 1 });
assert.equal(truncated.truncated, true);
assert.equal(truncated.cableLengthNm, 56, 'display cap does not truncate measured cable length');
assert.throws(() => parseSWC(raw, { ...options, nmPerUnit: undefined }));
assert.throws(() => parseSWC(raw + '1 1 0 0 0 1 -1', options), /duplicate/);
assert.throws(() => parseSWC('1 1 0 0 0 1 2', options), /parent/);
assert.throws(() => parseSWC('1 1 0 0 0 1 2\n2 1 0 0 0 1 1', options), /cycle/);
assert.throws(() => parseSWC('1 1 NaN 0 0 1 -1', options));
assert.throws(() => parseSWC('# empty', options));
console.log('swctest: PASS — exact units, specimen identity, parent validation, branches and honest truncation');
